// <auto-generated />
using CadastroVeiculos.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CadastroVeiculos.Infra.Data.Context.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CadastroVeiculos.Domain.Entities.Proprietario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Proprietario");
                });

            modelBuilder.Entity("CadastroVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.Property<Guid>("ProprietarioID");

                    b.Property<string>("Renavam")
                        .HasMaxLength(11);

                    b.HasKey("ID");

                    b.HasIndex("ProprietarioID");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("CadastroVeiculos.Domain.Entities.VeiculoFoto", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ArquivoID");

                    b.Property<Guid>("VeiculoID");

                    b.HasKey("ID");

                    b.HasIndex("VeiculoID");

                    b.ToTable("VeiculoFoto");
                });

            modelBuilder.Entity("CadastroVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("CadastroVeiculos.Domain.Entities.Proprietario", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CadastroVeiculos.Domain.Entities.VeiculoFoto", b =>
                {
                    b.HasOne("CadastroVeiculos.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Fotos")
                        .HasForeignKey("VeiculoID")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
